name: Tests Verification

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests=true

      - name: Run tests
        run: mvn test

      - name: Build project
        run: mvn clean install

      - name: Ensure code is formatted correctly (optional step)
        run: mvn checkstyle:check # Requires Maven Checkstyle Plugin

      - name: Verify package integrity
        run: mvn verify

      - name: Archive test reports (Optional, useful for debugging CI failures)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports
